# The default Terraform state key for backends that support it
terraform_state_key: "cluster/{{ cluster_id }}/tfstate"

# Set up the terraform backend
terraform_backend_type: "{{ 'consul' if 'CONSUL_HTTP_ADDR' in ansible_env else 'local' }}"
terraform_backend_config_defaults:
  consul:
    path: "{{ terraform_state_key }}"
    gzip: "true"
  local: {}
terraform_backend_config: "{{ terraform_backend_config_defaults[terraform_backend_type] }}"

terraform_binary_directory: "{{ playbook_dir }}/bin"
terraform_binary_path: "{{ terraform_binary_directory }}/terraform"
terraform_project_path: "{{ playbook_dir }}/terraform"

terraform_state: "{{ cluster_state | default('present') }}"

# The user that should be used to SSH to the cluster hosts
cluster_ssh_user: ipuuser

poplar_appliance_images:
  - name: "Ubuntu 20.04"
    friendly: "Focal"
    image_id: "fef180da-ca78-40b0-954a-10eca2ac831b"
  - name: "Ubuntu 18.04"
    friendly: "Bionic"
    image_id: "4c114921-9a0d-4411-8955-d2adc4dfbae5"
