---
- name: Populate inventory with VIPU server
  hosts: localhost
  tasks:
    - name: Add to inventory
      ansible.builtin.add_host:
        name: vipu_ctrl
        ansible_host: 10.129.110.13
        ansible_user: ipuuser
        groups: vipu_server

- name: Configure vipu server
  hosts: vipu_ctrl
  tasks:
    - name: Debug vipu server
      ansible.builtin.debug:
        var: ansible_facts
      ignore_unreachable: yes
      when:
        - terraform_state == "present"

    - name: Create allocation
      ansible.builtin.command:
        cmd: vipu-admin --showjson create allocation {{cluster_name}}-alloc --size {{allocation_size}}
      register: vipu_alloc_mk
      when:
        - terraform_state == "present"

    - name: Debug vipu-admin output
      ansible.builtin.debug:
        var: vipu_alloc_mk
      when:
        - vipu_alloc_mk is defined

    - name: List allocation
      ansible.builtin.command:
        cmd: vipu-admin --showjson list allocations
      register: vipu_alloc_list
      when:
        - terraform_state == "present"

    - name: Debug vipu-admin list
      ansible.builtin.debug:
        var: vipu_alloc_list
      when:
        - vipu_alloc_list is defined

- name: Provision infrastructure
  hosts: openstack
  roles:
    - cluster_infra
  post_tasks:
    - name: Wait for Monitoring to become available
      uri:
        url: "http://{{ zenith_fqdn_monitoring }}"
        method: GET
        follow_redirects: safe
      register: monitoring_uri
      changed_when: false
      failed_when: >-
        monitoring_uri.status < 0 or
        monitoring_uri.status == 404 or
        monitoring_uri.status >= 500
      retries: 60
      delay: 10
      # 404 and 503 are the statuses that are seen when the Zenith service is not ready yet
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      until: monitoring_uri.status not in [404, 503, -1]
      when: (cluster_state | default('present')) == 'present'
      tags: never

    - name: Wait for webconsole to become available
      uri:
        url: "http://{{ zenith_fqdn_webconsole }}"
        method: GET
        follow_redirects: safe
      register: webconsole_uri
      changed_when: false
      failed_when: >-
        webconsole_uri.status < 0 or
        webconsole_uri.status == 404 or
        webconsole_uri.status >= 500
      retries: 60
      delay: 10
      # 404 and 503 are the statuses that are seen when the Zenith service is not ready yet
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      until: webconsole_uri.status not in [404, 503, -1]
      when: (cluster_state | default('present')) == 'present'
      tags: never
