---
# This task list configures user-defined partitions, Azimuth-defined allocation
# and IPUMs when the Poplar Appliance is created (terraform_state == present)
- name: Make Terraform project directory
  file:
    path: "{{ terraform_project_path }}"
    state: directory

- name: Copy clouds.yaml file
  ansible.builtin.copy:
    decrypt: yes
    src: "{{playbook_dir}}/files/clouds-{{gc_cloud}}.yaml"
    #dest: "{{ terraform_project_path }}/clouds.yaml"
    dest: "~/.config/openstack/clouds.yaml"

- name: Get clouds.yaml file for debug
  ansible.builtin.slurp:
    src: "{{ terraform_project_path }}/clouds.yaml"
  register: slurpfile
  tags: [ debug, never ]

- name: Debug clouds.yaml file
  ansible.builtin.debug:
    msg: "{{ slurpfile['content'] | b64decode }}"
  tags: [ debug, never ]

- name: Can we get an allocation of requested size?
  ansible.builtin.command:
    cmd: /opt/gc/vipu-{{vipu_ver}}/vipu-admin -H {{ vipu_servers[appliance_tenancy]['floating_ip'] }} -P 8091 --showjson create allocation --options --size {{allocation_size}}
  ignore_errors: yes
  register: vipu_alloc_opt

- name: Debug allocation test
  ansible.builtin.debug:
    var: vipu_alloc_opt
  tags: [ debug, never ]

- name: Do we have any options
  ansible.builtin.fail:
    msg: No allocations of size {{allocation_size}} available
  when:
    - vipu_alloc_opt.rc != 0
    - '"no free allocation" in vipu_alloc_opt.stderr'

- name: Create allocation
  ansible.builtin.command:
    cmd: /opt/gc/vipu-{{vipu_ver}}/vipu-admin -H {{ vipu_servers[appliance_tenancy]['floating_ip'] }} -P 8091 --showjson create allocation {{allocation_name}} --size {{allocation_size}}
  register: vipu_alloc_mk

- name: Debug vipu-admin output
  ansible.builtin.debug:
    var: vipu_alloc_mk
  when:
    - vipu_alloc_mk is defined
  tags: [ debug, never ]

- name: Get allocation properties
  ansible.builtin.command:
    cmd: /opt/gc/vipu-{{vipu_ver}}/vipu-admin -H {{ vipu_servers[appliance_tenancy]['floating_ip'] }} -P 8091 --showjson get allocation {{allocation_name}}
  register: assigned_alloc

- name: List assigned IPUMs
  ansible.builtin.set_fact:
    assigned_ipums_list: "{{ assigned_alloc.stdout | from_json |  moreati.jq.jq('.allocation.spec.agent_ids') }}"

- name: Debug vipu-admin list
  ansible.builtin.debug:
    var: vipu_alloc_list
  when:
    - vipu_alloc_list is defined
  tags: [ debug, never ]

- name: Create partition if user requested
  block:
    - name: Create partition name
      ansible.builtin.set_fact:
        user_partition: "{{allocation_name}}-reconfig"

    - name: Create partition
      ansible.builtin.command:
        cmd: /opt/gc/vipu-{{vipu_ver}}/vipu-admin -H {{ vipu_servers[appliance_tenancy]['floating_ip'] }} -P 8091 --showjson create partition {{user_partition}} --size {{allocation_size}} --allocation {{allocation_name}} --reconfigurable
      register: vipu_part_mk
      ignore_errors: yes

    - name: Did we create the requested partition?
      ansible.builtin.fail:
        msg: Creating reconfigurable partition size {{allocation_size}} in {{allocation_name}}
      when:
        - vipu_alloc_mk.rc != 0
  when:
    - '"Single reconfigurable partition" in partition_choice'

- name: Shuffle IPUMs
  ansible.builtin.import_tasks: truffleshuffle.yml

- name: Remove clouds.yaml file so next play runs as the Azimuth user
  ansible.builtin.file:
    state: absent
    path: ~/.config/openstack/clouds.yaml
